<?php

namespace WPBR\App;

Enqueue::outputVars( [
    'ajaxUrl'  => admin_url( 'admin-ajax.php' ),
    'messages' => [
        'serverError'          => __( 'Unexpected server error.', 'wpbr' ),
        'pleaseWait'           => __( 'Please wait...', 'wpbr' ),
        'changesMade'          => __( 'Changes were made, you should save!', 'wpbr' ),
        'save'                 => __( 'Save settings', 'wpbr' ),
        'saved'                => __( 'Settings saved!', 'wpbr' ),
        'slotLength'           => __( 'Default slot length', 'wpbr' ),
        'slotLengthSub'        => __( 'Select default slot length that will be used to build timeslots for all services (this option is also customizable per service).', 'wpbr' ),
        'cancellationLimit'    => __( 'Default cancellation limit', 'wpbr' ),
        'cancellationLimitSub' => __( 'To prevent services from being cancelled too late you can pick time limit after which service won\'t be cancelable anymore (this option is also customizable per service).', 'wpbr' ),
        'defaultStatus'        => __( 'Default booking status', 'wpbr' ),
        'defaultStatusSub'     => __( 'Select default status that booking will have after being created.', 'wpbr' ),
        'requiredFields'       => __( 'Required fields', 'wpbr' ),
        'requiredFieldsSub'    => __( 'Select fields that will be required while creating bookings', 'wpbr' ),
        'firstDay'             => __( 'First day of week', 'wpbr' ),
        'firstDaySub'          => __( 'Select first day of week that will be displayed in calendar', 'wpbr' ),
        'paypalEnabled'        => __( 'Enable PayPal payment', 'wpbr' ),
        'paypalEnabledSub'     => __( 'Enable or disable payment via PayPal', 'wpbr' ),
        'paypalApiName'        => __( 'PayPal API name', 'wpbr' ),
        'paypalApiNameSub'     => __( 'Enter your PayPal API name', 'wpbr' ),
        'paypalApiSecret'      => __( 'PayPal API secret', 'wpbr' ),
        'paypalApiSecretSub'   => __( 'Enter your PayPal API secret', 'wpbr' ),
        'paypalType'           => __( 'Paypal type', 'wpbr' ),
        'paypalTypeSub'        => __( 'Select PayPal environment (sandbox or production)', 'wpbr' ),
        'paymentOnArrival'     => __( 'Payment on arrival', 'wpbr' ),
        'paymentOnArrivalSub'  => __( 'Enable payment on arrival', 'wpbr' ),
        'googleEnabled'        => __( 'Google Calendar and Google Maps Integration' ),
        'googleEnableSub'      => __( 'Enable integration with Google Calendar and Google Maps. Bookings will be synced in a 2-way synchronization. You will be also able to mark service location using Google Maps.' ),
        'googleApi'            => __( 'Google API code' ),
        'googleApiSub'         => __( 'Provide your Google API code' ),
        'googleOAuthLogin'     => __( 'Google OAuth Login', 'wpbr' ),
        'googleOAuthLoginSub'  => __( 'Provide your Google OAuth Login', 'wpbr' ),
        'googleOAuthSecret'    => __( 'Google OAuth Secret', 'wpbr' ),
        'googleOAuthSecretSub' => __( 'Provide you Google OAuth Secret' ),
        'enabled'              => __( 'Enabled', 'wpbr' ),
    ],
    'fields'   => apply_filters( 'wpbr/settings/fields', [
        'general'      => [
            'slotLengths'     => [
                '15 mins'  => __( '15 mins', 'wpbr' ),
                '30 mins'  => __( '30 mins', 'wpbr' ),
                '45 mins'  => __( '45 mins', 'wpbr' ),
                '60 mins'  => __( '1 hour', 'wpbr' ),
                '2 hours'  => __( '1 hours', 'wpbr' ),
                '3 hours'  => __( '3 hours', 'wpbr' ),
                '6 hours'  => __( '6 hours', 'wpbr' ),
                '12 hours' => __( '12 hours', 'wpbr' ),
            ],
            'cancelLengths'   => [
                '15 mins'  => __( '15 mins', 'wpbr' ),
                '30 mins'  => __( '30 mins', 'wpbr' ),
                '45 mins'  => __( '45 mins', 'wpbr' ),
                '60 mins'  => __( '60 mins', 'wpbr' ),
                '2 hours'  => __( '1 hour', 'wpbr' ),
                '3 hours'  => __( '3 hours', 'wpbr' ),
                '6 hours'  => __( '6 hours', 'wpbr' ),
                '12 hours' => __( '12 hours', 'wpbr' ),
                '24 hours' => __( '24 hours', 'wpbr' ),
                '2 days'   => __( '2 days', 'wpbr' ),
                '3 days'   => __( '3 days', 'wpbr' ),
                '5 days'   => __( '5 days', 'wpbr' ),
                '6 days'   => __( '6 days', 'wpbr' ),
                '1 week'   => __( '1 week', 'wpbr' ),
                '2 weeks'  => __( '2 weeks', 'wpbr' ),
                '3 weeks'  => __( '3 weeks', 'wpbr' ),
                '4 weeks'  => __( '4 weeks', 'wpbr' ),
                '5 weeks'  => __( '5 weeks', 'wpbr' ),
                '6 weeks'  => __( '6 weeks', 'wpbr' ),
            ],
            'bookingStatuses' => [
                'pending'  => __( 'Pending', 'wpbr' ),
                'approved' => __( 'Approved', 'wpbr' ),
            ],
            'fields'          => [
                'firstName'   => __( 'First name', 'wpbr' ),
                'lastName'    => __( 'Last name', 'wpbr' ),
                'phoneNumber' => __( 'Phone number', 'wpbr' ),
            ],
        ],
        'calendar'     => [
            'days' => [
                '0' => __( 'Sunday', 'wpbr' ),
                '1' => __( 'Monday', 'wpbr' ),
                '2' => __( 'Tuesday', 'wpbr' ),
                '3' => __( 'Wednesday', 'wpbr' ),
                '4' => __( 'Thursday', 'wpbr' ),
                '5' => __( 'Friday', 'wpbr' ),
                '6' => __( 'Saturday', 'wpbr' ),
            ],
        ],
        'payment'      => [
            'paypalTypes' => [
                'sandbox'    => __( 'Sandbox', 'wpbr' ),
                'production' => __( 'Production', 'wpbr' ),
            ],
        ],
        'integrations' => [

        ],
    ] ),
], 'WPBRVars' );
